### ISSUE TITLE
Question: What is the purpose of the `annotation` record?

### ISSUE THREAD

**Issue by amirouche** [weinholt/laesare#1]
Hello,

I am looking at the following code:

https://github.com/weinholt/laesare/blob/632e1de836d91658e4e83c036ee22887e4547d54/reader.sls#L115-L119

I am wondering what is its purpose. Does laesare integrate with chez reader somehow?

**Comment by weinholt** [comment]
This annotation type comes from what psyntax wants as input. I'm using it in a compiler and in r6lint. It doesn't have anything to do with Chez as such. But Chez has mechanisms for working with your own annotations, so it should be possible to integrate them.

**Comment by amirouche** [comment]
Thank you!
